require conf/distro/poky.conf

DISTRO = "maria-distro"
DISTRO_NAME = "Maria Linux (Poky-based)"
DISTRO_VERSION = "1.0.0"
DISTRO_CODENAME = "scarthgap"

# Override these in poky-based distros
POKY_DEFAULT_DISTRO_FEATURES = ""
POKY_DEFAULT_EXTRA_RDEPENDS = "packagegroup-core-boot"
POKY_DEFAULT_EXTRA_RRECOMMENDS = ""

INIT_MANAGER = "systemd"
